### ISSUE TITLE
Support passing URLs via path rather than querystring

### ISSUE THREAD

**Issue by johnboxall** [biesiad/deelay-ruby#1]
Cool service thanks!

Currently if you're trying to use deelay.me as the endpoint for an HTTP resource used in a jQuery JSONP request, you're going to have a bad time!

```
$.ajax("http://deelay.me/1000?http://foo.bar/");
```

This results in a HTTP to deelay.me: http://deelay.me/1000?http://foo.bar/&callback=jQuery123...

Which results in a HTTP to foo.bar: http://foo.bar/&callback=jQuery123...

Note how the querystring has been incorrectly passed : (

If instead the service allow passing URLs by path, things would work perfectly:

http://deelay.me/1000/http://foo.bar/

**Comment by biesiad** [comment]
Yeah, I've been getting similar requests. I'm leaving the issue open for a reminder and will work on it when I have some spare time. Feel free to hack and send a PR.

**Comment by biesiad** [comment]
Added passing URL by path. Check out test suite for examples (https://github.com/biesiad/deelay/blob/master/test/test_deelay_app.rb#L39). It's only in the gem now, not available on deelay.me service yet.

**Comment by biesiad** [comment]
It's now also available on the http://deelay.me service.
