### ISSUE TITLE
Option for slow load instead of delayed load

### ISSUE THREAD

**Issue by tgr** [biesiad/deelay-ruby#2]
It would be nice if there was an option for slow instead of delayed loading; that is, instead of waiting for $delay and then sending the file normally, the server would start sending immediately but do it so slowly that it took $delay to finish. This would help with testing incremental image loading or tools like [clarinet](https://github.com/dscape/clarinet).

**Comment by biesiad** [comment]
Idea behind deelay was to make a tool for quick and dirty testing. There are more sophisticated tool that will provide you features you are talking about. Try [Fiddler](http://www.telerik.com/fiddler) or [Charles](http://www.charlesproxy.com/) for more control.
