### ISSUE TITLE
https redirection doesn't work

### ISSUE THREAD

**Issue by cmheisel** [biesiad/deelay-ruby#7]
When you put a https URL behind deelay, the redirected URL gets munged to http://https:/domain

Steps to reproduce:
- curl -vvv http://www.deelay.me/1000/https://www.google.com/
  - Location is "Location: http://https:/www.google.com/"
  - Location should be "Location: https:/www.google.com/"

**Comment by biesiad** [comment]
Sorry, I forgot about this report. @cmheisel, do you perhaps have a branch that fixes this?

**Comment by biesiad** [comment]
Fixed with 80fd291e715049b9685a7b122fb4347ff645ddd7.
