### ISSUE TITLE
Make it possible to delay resources over https or http/2 

### ISSUE THREAD

**Issue by ixisio** [biesiad/deelay-ruby#8]
I will test delayed resources in a http/2 (https) environment and unfortunately deelay.me only works over http.

Thanks for this awesome mini tool!

Cheers
Andy

**Comment by biesiad** [comment]
Thanks for the note. I'd have to buy an ssl certificate to enable https redirections. I'll do it as soon as I find a way to monetize the service. Unfortunately, donate button I put up some time ago didn't attract too much attention. To be more precise, it earned $0. There's really no workaround for now :(
Greg

**Comment by ixisio** [comment]
Really understand that!
Thanks for replying...

Andy
